//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppName {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppName.DemoAppResources", typeof(DemoAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new contact to your app, organization or team. This form has been designed to simplify a commonly used page in mobile apps..
        /// </summary>
        internal static string AddContactPageDescription {
            get {
                return ResourceManager.GetString("AddContactPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a classic article view, it displays a featured image and a toolbar with key stats. It&apos;s a simple but useful layout..
        /// </summary>
        internal static string ArticleDetailPageDescription {
            get {
                return ResourceManager.GetString("ArticleDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful way to display content. Perfect to be used as the main navigation for travels and tourism related content..
        /// </summary>
        internal static string ArticlesBrowserPageDescription {
            get {
                return ResourceManager.GetString("ArticlesBrowserPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to display either articles or documentation. It&apos;s a commonly used pattern to display an overview of items..
        /// </summary>
        internal static string ArticlesClassicViewPageDescription {
            get {
                return ResourceManager.GetString("ArticlesClassicViewPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to display either articles or documentation. This particular view displays a featured article at the top of the page, and in landscape changes layout to show more columns..
        /// </summary>
        internal static string ArticlesColumnPageDescription {
            get {
                return ResourceManager.GetString("ArticlesColumnPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This variation of the articles view is based on a Twitter-like feed. Each card has an author, featured image, title, and date..
        /// </summary>
        internal static string ArticlesFeedPageDescription {
            get {
                return ResourceManager.GetString("ArticlesFeedPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This variation of article list can also be used to show any kind of product, service, or recipe photo. You can also remove the pictures and use a solid color background..
        /// </summary>
        internal static string ArticlesListPageDescription {
            get {
                return ResourceManager.GetString("ArticlesListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a clean view of Grial layouts..
        /// </summary>
        internal static string BlackboardThemeDescription {
            get {
                return ResourceManager.GetString("BlackboardThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chill vibe for your app..
        /// </summary>
        internal static string BlackSunThemeDescription {
            get {
                return ResourceManager.GetString("BlackSunThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse samples.
        /// </summary>
        internal static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what&apos;s new.
        /// </summary>
        internal static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delicate choice for your app..
        /// </summary>
        internal static string CabernetLightThemeDescription {
            get {
                return ResourceManager.GetString("CabernetLightThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect to display any kind of content the Card Article page template display a modern look and feel. Perfect to show food recipes..
        /// </summary>
        internal static string CardArticlePageDescription {
            get {
                return ResourceManager.GetString("CardArticlePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean but effective design. Showcasing Grial Custom Tab control. This is a great example of a simple UI design..
        /// </summary>
        internal static string ChatMainPageDescription {
            get {
                return ResourceManager.GetString("ChatMainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by most commonly used chat applications like Skype, Telegram, Whatsapp, Slack, and so many others..
        /// </summary>
        internal static string ChatMessagesListPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of template that will save you countless hours of design and implementation..
        /// </summary>
        internal static string ChatMessagesPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Chat Timeline page is desgined to show a conversation or interaction. Use it to display interactions or workflows..
        /// </summary>
        internal static string ChatTimelinePageDescription {
            get {
                return ResourceManager.GetString("ChatTimelinePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are planning to sell anything through your app, you will probably need this template..
        /// </summary>
        internal static string CheckoutPageDescription {
            get {
                return ResourceManager.GetString("CheckoutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple but beautiful designed contact details page. It can be also used as a profile page..
        /// </summary>
        internal static string ContactDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple but beautiful designed contact details page. It can be also used as a profile page..
        /// </summary>
        internal static string ContactSimpleDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactSimpleDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Blog Article page was designed to showcase tours, trips or similar kind of experiences..
        /// </summary>
        internal static string CurvedHeaderArticlePageDescription {
            get {
                return ResourceManager.GetString("CurvedHeaderArticlePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple custom Activity Indicator. Change the content as you wish..
        /// </summary>
        internal static string CustomActivityIndicatorPageDescription {
            get {
                return ResourceManager.GetString("CustomActivityIndicatorPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple page that lists all available Grial custom renderers..
        /// </summary>
        internal static string CustomRenderersPageDescription {
            get {
                return ResourceManager.GetString("CustomRenderersPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple settings page. Use this page as a basic settings display page..
        /// </summary>
        internal static string CustomSettingsPageDescription {
            get {
                return ResourceManager.GetString("CustomSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional look for your screens..
        /// </summary>
        internal static string DarkThemeDescription {
            get {
                return ResourceManager.GetString("DarkThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to display any kind of article, service, document or product. Every item on the grid has an author, a brief description and featured image..
        /// </summary>
        internal static string DashboardCardsPageDescription {
            get {
                return ResourceManager.GetString("DashboardCardsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful dashboard with a carousel view on top. Use it to display categories and eye catching content..
        /// </summary>
        internal static string DashboardCarouselPageDescription {
            get {
                return ResourceManager.GetString("DashboardCarouselPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this a beautiful navigation grid with icons, images, and data. Use this page to display different tiles to navigate to apps, locations or just to show messages previews..
        /// </summary>
        internal static string DashboardMultipleTilesPageDescription {
            get {
                return ResourceManager.GetString("DashboardMultipleTilesPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Binaria Wallet.
        /// </summary>
        internal static string DemoAppPageTitleAbout {
            get {
                return ResourceManager.GetString("DemoAppPageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list with all our gorgeous themes where you can choose any of them..
        /// </summary>
        internal static string DemoSettingsPageDescription {
            get {
                return ResourceManager.GetString("DemoSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This timeline was designed to show actions over a document. Use it to show a clear sequence of actions performed over any item, i.e a transaction..
        /// </summary>
        internal static string DocumentTimelinePageDescription {
            get {
                return ResourceManager.GetString("DocumentTimelinePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a perfect layout to use on any kind of store app. It includes a search field and a top area to display offers or featured products..
        /// </summary>
        internal static string EcommerceMainPageDescription {
            get {
                return ResourceManager.GetString("EcommerceMainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From employees to products, this form layout it&apos;s a nice way to add anything in your app..
        /// </summary>
        internal static string EmployeeFormPageDescription {
            get {
                return ResourceManager.GetString("EmployeeFormPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean example useful to show Employee Performance details. Add, remove and customize it according to your specific needs..
        /// </summary>
        internal static string EmployeePerformanceDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeePerformanceDashboardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean example useful to show Employee Performance details. Add, remove and customize it according to your specific needs..
        /// </summary>
        internal static string EmployeeProfileDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeeProfileDashboardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a simple but useful view. Use it to notify your users when something went wrong or something has changed..
        /// </summary>
        internal static string EmptyStatePageDescription {
            get {
                return ResourceManager.GetString("EmptyStatePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your still imagery come to life by adding our Ken Burns behavior. Easily get this panning and zooming effect in your images, icons or any view in your app through this behavior. Use our Pulse behavior to highlight important pieces of UI so your users don&apos;t miss anything..
        /// </summary>
        internal static string FeatureAnimationLoopsDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Loop Behaviors.
        /// </summary>
        internal static string FeatureAnimationLoopsTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily incorporate our animations API and add life to your app. Create lovely and engaging UXs on user scroll. Translate or rotate items, change their colors, fade and scale them to achieve outstanding parallax effects. The combinations are infinite, and your users will love your app..
        /// </summary>
        internal static string FeatureAnimationsViewDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations.
        /// </summary>
        internal static string FeatureAnimationsViewTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the most used mobile UI patterns now simplified and available for Xamarin Forms through XAML. Define the shadow color, shadow blur, and corner radius, set the background color and use it as a container for any of your contents..
        /// </summary>
        internal static string FeatureCardViewDescription {
            get {
                return ResourceManager.GetString("FeatureCardViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card View.
        /// </summary>
        internal static string FeatureCardViewTitle {
            get {
                return ResourceManager.GetString("FeatureCardViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a collection of subviews in your page through the Carousel View. It is fully customizable and supports progressive animations allowing to change your content on user drag events, enabling rich UIs for your app that your users will enjoy..
        /// </summary>
        internal static string FeatureCarouselViewDescription {
            get {
                return ResourceManager.GetString("FeatureCarouselViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel View.
        /// </summary>
        internal static string FeatureCarouselViewTitle {
            get {
                return ResourceManager.GetString("FeatureCarouselViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data visualization to your app through our beautifully styled charts. Easily change colors and bind your data through our helpers and wrappers from XAML code..
        /// </summary>
        internal static string FeatureChartsDescription {
            get {
                return ResourceManager.GetString("FeatureChartsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string FeatureChartsTitle {
            get {
                return ResourceManager.GetString("FeatureChartsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your UI interaction needs in Xamarin Forms by including single and multiple user selection through checkboxes and radios with fully customizable XAML templates. Change colors, styles, sizes to suit your needs. Take your data forms pages to the next level..
        /// </summary>
        internal static string FeatureCheckboxesAndRadiosDescription {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes and Radios.
        /// </summary>
        internal static string FeatureCheckboxesAndRadiosTitle {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have more control over common Xamarin Forms controls to make them look exactly as you need them. We added more styling properties to controls such as editor, entry, pickers, searchbar and more..
        /// </summary>
        internal static string FeatureCustomRenderersDescription {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Renderers.
        /// </summary>
        internal static string FeatureCustomRenderersTitle {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display tabular data with our cross-platform Data Grid. Easily customize its look and feel through XAML properties such as odd row color, header background color, etc., or go deeper into customization using templates for cells, columns, headers, etc. It allows sorting and selection..
        /// </summary>
        internal static string FeatureDataGridDescription {
            get {
                return ResourceManager.GetString("FeatureDataGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        internal static string FeatureDataGridTitle {
            get {
                return ResourceManager.GetString("FeatureDataGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delight your users with this beautifully designed content navigation. Use it to display any kind of product or services inside your app..
        /// </summary>
        internal static string FeaturedMoviesPageDescription {
            get {
                return ResourceManager.GetString("FeaturedMoviesPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A great new addition to allow further styling and customization of your app. No need to create images. Linear and radial gradients are now available in XAML through our expressive API: define the colors, color stops, opacity, angles, relative or absolute positioning in a similar fashion as in CSS..
        /// </summary>
        internal static string FeatureGradientsViewDescription {
            get {
                return ResourceManager.GetString("FeatureGradientsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradients.
        /// </summary>
        internal static string FeatureGradientsViewTitle {
            get {
                return ResourceManager.GetString("FeatureGradientsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our newest addition to the kit: the flows can be seen as micro apps that cover typical patterns and UX. They contain a certain number of related screens, templates and UI controls, that work together in harmony as a unit. Messages, movie catalog, tasks dashboard and e-commerce flows are available..
        /// </summary>
        internal static string FeatureGrialFlowsDescription {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Flows .
        /// </summary>
        internal static string FeatureGrialFlowsTitle {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the most requested features for Xamarin Forms finally is here: now you can make your navigation bar fully transparent, or simulate a taller bar. You can combine its power by using our new XAML gradients and animations to make gorgeous and engaging UIs..
        /// </summary>
        internal static string FeatureGrialNavbarViewDescription {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Navbar.
        /// </summary>
        internal static string FeatureGrialNavbarViewTitle {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bindable and dynamic UI control that inherits from Grid. It allows to easily control how column and rows rendered from a bound data source..
        /// </summary>
        internal static string FeatureGridViewDescription {
            get {
                return ResourceManager.GetString("FeatureGridViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View .
        /// </summary>
        internal static string FeatureGridViewTitle {
            get {
                return ResourceManager.GetString("FeatureGridViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial based apps are localizable by default, which means they support different languages effortlessly. We provide a XAML markup extension to consume strings from RESX files and runtime options to change the app language..
        /// </summary>
        internal static string FeatureI18nDescription {
            get {
                return ResourceManager.GetString("FeatureI18nDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try the RTL button on top to see the app in arabic!.
        /// </summary>
        internal static string FeatureI18nInvite {
            get {
                return ResourceManager.GetString("FeatureI18nInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i18n.
        /// </summary>
        internal static string FeatureI18nTitle {
            get {
                return ResourceManager.GetString("FeatureI18nTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial 3 provides 8 fonts containing more than free 5K icons available from XAML! Icons are provided in different styles: filled, line, matching look and feel for material design and iOS. They will render sharply across different devices with different pixel densities and resolutions, making this a very flexible and maintainable way that avoids generating lots of bitmaps..
        /// </summary>
        internal static string FeatureIconsDescription {
            get {
                return ResourceManager.GetString("FeatureIconsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons .
        /// </summary>
        internal static string FeatureIconsTitle {
            get {
                return ResourceManager.GetString("FeatureIconsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A full collection of beautiful dialogs and pop-us made in XAML, fully customizable and themeable. It covers the most typical use cases such as: notifications, user feedback, irregular dialogs, custom action sheets, and more..
        /// </summary>
        internal static string FeaturePopupsDescription {
            get {
                return ResourceManager.GetString("FeaturePopupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop Ups.
        /// </summary>
        internal static string FeaturePopupsTitle {
            get {
                return ResourceManager.GetString("FeaturePopupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string FeaturePoweredBy {
            get {
                return ResourceManager.GetString("FeaturePoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layout that allows repeating content inside. It supports bindings, data templates, horizontal and vertical orientation, items selection and virtualization..
        /// </summary>
        internal static string FeatureRepeaterDescription {
            get {
                return ResourceManager.GetString("FeatureRepeaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeater.
        /// </summary>
        internal static string FeatureRepeaterTitle {
            get {
                return ResourceManager.GetString("FeatureRepeaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have full control over how your UI renders across multiple devices, platforms and screen orientations. Control how your page’s content flow. Set your font sizes, alignments, margins, paddings and almost every possible property for each specific case..
        /// </summary>
        internal static string FeatureResponsiveHelpersDescription {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Helpers.
        /// </summary>
        internal static string FeatureResponsiveHelpersTitle {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages come with support for right-to-left languages with the same XAML code. Yes! A single XAML codebase that works for both LTR and RTL with no duplicated chunks of code, conditional visibilities or other complexities. We also provide the option to change the layout direction at runtime as a user preference..
        /// </summary>
        internal static string FeatureRTLDescription {
            get {
                return ResourceManager.GetString("FeatureRTLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try the RTL button on top to see the app with a right-to-left layout..
        /// </summary>
        internal static string FeatureRtlInvite {
            get {
                return ResourceManager.GetString("FeatureRtlInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-to-left.
        /// </summary>
        internal static string FeatureRTLTitle {
            get {
                return ResourceManager.GetString("FeatureRTLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Xamarin Forms effects provide fine-grained control to adjust your page content to the device safe area insets making sure it&apos;s never clipped by the rounded corners or the home indicator. The background elements can cover every pixel of the screen and through optional paddings you avoid actual content clipping..
        /// </summary>
        internal static string FeatureSafeAreaEffectDescription {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS Safe Area Effects.
        /// </summary>
        internal static string FeatureSafeAreaEffectTitle {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch views inside your page easily by alternating content visibility. Default look and feel matching Android and iOS and their native positioning. Fully customizable appearance through XAML templates and styles. Icon support. Full width or AutoScrollable, no matter how many tabs you add they will scroll automatically..
        /// </summary>
        internal static string FeatureTabControlDescription {
            get {
                return ResourceManager.GetString("FeatureTabControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Control.
        /// </summary>
        internal static string FeatureTabControlTitle {
            get {
                return ResourceManager.GetString("FeatureTabControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A complete cross-platform video player available in Xamarin Forms and fully skinnable through XAML. You can use it as a background for your page, or simply to show a video feed. Easily reproduce local or remote videos in a variety of formats including Youtube..
        /// </summary>
        internal static string FeatureVideoPlayerDescription {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player .
        /// </summary>
        internal static string FeatureVideoPlayerTitle {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our wrap-panel layout allows displaying wrapped content inside. It arranges its children horizontally inside it, and then wraps the display of subsequent children to additional rows. Supports templates, bindings or XAML content directly..
        /// </summary>
        internal static string FeatureWrapPanelDescription {
            get {
                return ResourceManager.GetString("FeatureWrapPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Panel.
        /// </summary>
        internal static string FeatureWrapPanelTitle {
            get {
                return ResourceManager.GetString("FeatureWrapPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a classic navigation grid with icons. Use is it as the main screen of your app. Useful to show users an easy way to navigate through your app..
        /// </summary>
        internal static string FlatDashboardPageDescription {
            get {
                return ResourceManager.GetString("FlatDashboardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful and simple ecommerce flow, featuring product detail, order confirmation, product checkout and purchase notification..
        /// </summary>
        internal static string FlowDescriptionEcommerce {
            get {
                return ResourceManager.GetString("FlowDescriptionEcommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle the messages and notifications of your mobile app in a beautiful and simple way. Save time with message flow..
        /// </summary>
        internal static string FlowDescriptionMessages {
            get {
                return ResourceManager.GetString("FlowDescriptionMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the power of animations, and visual effects in this super polished example of movies navigation..
        /// </summary>
        internal static string FlowDescriptionMovies {
            get {
                return ResourceManager.GetString("FlowDescriptionMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks performance overview dashboard. Team performance overview and team member details..
        /// </summary>
        internal static string FlowDescriptionTasks {
            get {
                return ResourceManager.GetString("FlowDescriptionTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylish and simple Login Page. Add some branding with a simple image in the background..
        /// </summary>
        internal static string FullBackgroundLoginPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundLoginPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are building an app that handles multiple providers this form will be a very useful one to have..
        /// </summary>
        internal static string FullBackgroundSignupPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundSignupPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page combines different ways to perfectly display any kind of content in a beautiful and balanced UI with an eye-catching parallax effect..
        /// </summary>
        internal static string FullHeaderArticlePagePageDescription {
            get {
                return ResourceManager.GetString("FullHeaderArticlePagePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this template to display general info about your mobile application..
        /// </summary>
        internal static string GenericAboutPageDescription {
            get {
                return ResourceManager.GetString("GenericAboutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for .NET Developers. this provides a complete ready made collection of fully customizable layouts, components, templates and resources to help developers and companies build beautiful cross-platform mobile app using Xamarin.Forms..
        /// </summary>
        internal static string GrialAboutDescription {
            get {
                return ResourceManager.GetString("GrialAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are eager to hear about your experiences working with Xamarin. 
        ///        
        ///Don’t be shy and say hello!.
        /// </summary>
        internal static string GrialAboutEagerToHear {
            get {
                return ResourceManager.GetString("GrialAboutEagerToHear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on:.
        /// </summary>
        internal static string GrialAboutFollowUs {
            get {
                return ResourceManager.GetString("GrialAboutFollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  community..
        /// </summary>
        internal static string GrialAboutGrialCommunity {
            get {
                return ResourceManager.GetString("GrialAboutGrialCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  powered by the awesome .
        /// </summary>
        internal static string GrialAboutGrialPoweredBy {
            get {
                return ResourceManager.GetString("GrialAboutGrialPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third party packages.
        /// </summary>
        internal static string GrialAboutGrialThirdParty {
            get {
                return ResourceManager.GetString("GrialAboutGrialThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial uses these .
        /// </summary>
        internal static string GrialAboutGrialUses {
            get {
                return ResourceManager.GetString("GrialAboutGrialUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a team designers and developers on a mission: taking Xamarin.Forms apps to the next level while having fun, becoming better, healthy, happier people in the process..
        /// </summary>
        internal static string GrialAboutMission {
            get {
                return ResourceManager.GetString("GrialAboutMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say Hello.
        /// </summary>
        internal static string GrialAboutSayHello {
            get {
                return ResourceManager.GetString("GrialAboutSayHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team is also well known for our XAML Previsualization tool, Gorilla Player..
        /// </summary>
        internal static string GrialAboutTeam {
            get {
                return ResourceManager.GetString("GrialAboutTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrialKit 3.0 not only gives you gorgeous animations, styling, and tons of layouts, but it teaches you amazing techniques for delivering next level mobile experiences..
        /// </summary>
        internal static string GrialAboutTestimonialDavidOrtinau {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialDavidOrtinau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am blown away by how good looking and easy to use GrialKit is. Do yourself a favor and check it out..
        /// </summary>
        internal static string GrialAboutTestimonialMiguelDeIcaza {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialMiguelDeIcaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural look of Grial layouts..
        /// </summary>
        internal static string HazeThemeDescription {
            get {
                return ResourceManager.GetString("HazeThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a classic navigation grid with icons. Use is it as the main screen of your app. Useful to show users an easy way to navigate through your app..
        /// </summary>
        internal static string IconsDashboardPageDescription {
            get {
                return ResourceManager.GetString("IconsDashboardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to overview all available icons in Grial..
        /// </summary>
        internal static string IconsPageDescription {
            get {
                return ResourceManager.GetString("IconsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a classic navigation grid with background images and icons. Use is it as the main screen of your app. Useful to show users an easy way to navigate through your app..
        /// </summary>
        internal static string ImagesDashboardPageDescription {
            get {
                return ResourceManager.GetString("ImagesDashboardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your eyes cry of happiness!.
        /// </summary>
        internal static string LightThemeDescription {
            get {
                return ResourceManager.GetString("LightThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Login Page is both useful and simple. Add or remove controls and content as you need..
        /// </summary>
        internal static string LoginPageDescription {
            get {
                return ResourceManager.GetString("LoginPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Binaria.
        /// </summary>
        internal static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls and features.
        /// </summary>
        internal static string MainMenuControlsAndFeatures {
            get {
                return ResourceManager.GetString("MainMenuControlsAndFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom controls.
        /// </summary>
        internal static string MainMenuCustomControls {
            get {
                return ResourceManager.GetString("MainMenuCustomControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main dashboard.
        /// </summary>
        internal static string MainMenuDashboard {
            get {
                return ResourceManager.GetString("MainMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial themes.
        /// </summary>
        internal static string MainMenuGrialThemes {
            get {
                return ResourceManager.GetString("MainMenuGrialThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All icons.
        /// </summary>
        internal static string MainMenuIcons {
            get {
                return ResourceManager.GetString("MainMenuIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        internal static string MainMenuWhatsNew {
            get {
                return ResourceManager.GetString("MainMenuWhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by commonly used chat applications, this is a list of conversations. Each list item shows a contact and its last message..
        /// </summary>
        internal static string MessagesListPageDescription {
            get {
                return ResourceManager.GetString("MessagesListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item detail page displays a featured item and related information such as description, rating and related items. Use it to display any kind of product, document or service..
        /// </summary>
        internal static string MovieDetailPageDescription {
            get {
                return ResourceManager.GetString("MovieDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by Netflix and Spotify, this page displays a featured item and multiple horizontal scrollable lists of movies. Use it to display a large amount of items previews such books, documents, movies or audio files..
        /// </summary>
        internal static string MoviesMainPageDescription {
            get {
                return ResourceManager.GetString("MoviesMainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A detailed navigation list showing title, description and tags. Use it to display details about inner content..
        /// </summary>
        internal static string NavigationCardsDescriptionListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsDescriptionListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A good looking card list menu is always effective to show different categories of items. For example, different store departments or different document categories..
        /// </summary>
        internal static string NavigationCardsListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A good looking list menu is always effective to show different categories of items. For example, different store departments or different document categories..
        /// </summary>
        internal static string NavigationFlatListPageDescription {
            get {
                return ResourceManager.GetString("NavigationFlatListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example shows a simple list menu with icons, titles and a number preview. Use it to show different categories of products, services or documents..
        /// </summary>
        internal static string NavigationListWithIconsPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithIconsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A good looking list menu is always effective to show different categories of items. For example, different store departments or different document categories..
        /// </summary>
        internal static string NavigationListWithImagesPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithImagesPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications page it&apos;s always useful in any app. Updates, policy changes, password updates, etc..
        /// </summary>
        internal static string NotificationsPageDescription {
            get {
                return ResourceManager.GetString("NotificationsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful in any E-commerce app: an order confirmation is always needed..
        /// </summary>
        internal static string OrderConfirmationPageDescription {
            get {
                return ResourceManager.GetString("OrderConfirmationPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nice and clean form page to add organization data..
        /// </summary>
        internal static string OrganizationFormPageDescription {
            get {
                return ResourceManager.GetString("OrganizationFormPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Your Theme.
        /// </summary>
        internal static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple password recovery page. Add or remove controls and content as you need..
        /// </summary>
        internal static string PasswordRecoveryPageDescription {
            get {
                return ResourceManager.GetString("PasswordRecoveryPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a quick overview of team tasks. This great example showcases a lot of cool stuff, including our Data Grid control..
        /// </summary>
        internal static string PerformanceDashboardMainPageDescription {
            get {
                return ResourceManager.GetString("PerformanceDashboardMainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A complete set of Pop Up designs to include in your app. From user feedback to multiple choice forms..
        /// </summary>
        internal static string PopupsPageDescription {
            get {
                return ResourceManager.GetString("PopupsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product display page has it all. If you are building an app that showcases products or services, this a must-have page..
        /// </summary>
        internal static string ProductDetailPageDescription {
            get {
                return ResourceManager.GetString("ProductDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very useful to show product pictures and short descriptions. Use it to show product details..
        /// </summary>
        internal static string ProductImageFullScreenPageDescription {
            get {
                return ResourceManager.GetString("ProductImageFullScreenPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple but useful way to show content. In this example, we choose to show a product. Featured image, title, price, and description..
        /// </summary>
        internal static string ProductItemViewPageDescription {
            get {
                return ResourceManager.GetString("ProductItemViewPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a useful page if you are planning to sell other products or services through the app..
        /// </summary>
        internal static string ProductOrderPageDescription {
            get {
                return ResourceManager.GetString("ProductOrderPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple but useful way to show content. In this example, we choose to show a product. Browse more related products swiping..
        /// </summary>
        internal static string ProductsCarouselPageDescription {
            get {
                return ResourceManager.GetString("ProductsCarouselPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A common UI to showcase products or collections. Use it to display either product or services..
        /// </summary>
        internal static string ProductsCatalogPageDescription {
            get {
                return ResourceManager.GetString("ProductsCatalogPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a useful page if you are planning to sell other products or services through the app..
        /// </summary>
        internal static string ProductsGridPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is inspired by a common products showcase pattern. Use to showcase either products or services in your app..
        /// </summary>
        internal static string ProductsGridVariantPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridVariantPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this user profile page to display a bio and some key stats of a person, product or service. Use large pictures to take the best out of this view..
        /// </summary>
        internal static string ProfilePageTimelinePageDescription {
            get {
                return ResourceManager.GetString("ProfilePageTimelinePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by commonly used chat applications, this is a list of conversations. Each list item shows a contact and its last message..
        /// </summary>
        internal static string RecentChatListPageDescription {
            get {
                return ResourceManager.GetString("RecentChatListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Responsive Helpers will allow you to take full control of how things layout on your pages, different devices, orientations, and platforms..
        /// </summary>
        internal static string ResponsiveHelpersPageDescription {
            get {
                return ResourceManager.GetString("ResponsiveHelpersPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An eye catching about page with nice parallax and scroll animations. Use this template to display general info about your mobile application..
        /// </summary>
        internal static string RichAboutPageDescription {
            get {
                return ResourceManager.GetString("RichAboutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens {0}.
        /// </summary>
        internal static string ScreenCount {
            get {
                return ResourceManager.GetString("ScreenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple settings page. Use this page as a basic settings display page..
        /// </summary>
        internal static string SettingsPageDescription {
            get {
                return ResourceManager.GetString("SettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautifully presented list of tasks and related data. This page uses Grial Data Grid control and Grial Custom Tab Control..
        /// </summary>
        internal static string ShippingDetailPageDescription {
            get {
                return ResourceManager.GetString("ShippingDetailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple Sign Up page to register new users into your app. Add or remove controls and content as you need..
        /// </summary>
        internal static string SignUpPageDescription {
            get {
                return ResourceManager.GetString("SignUpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Login Page is both useful and simple. Add or remove controls and content as you need..
        /// </summary>
        internal static string SimpleLoginPageDescription {
            get {
                return ResourceManager.GetString("SimpleLoginPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple Sign Up page to register new users into your app. Add or remove controls and content as you need..
        /// </summary>
        internal static string SimpleSignUpPageDescription {
            get {
                return ResourceManager.GetString("SimpleSignUpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classic among modern mobile apps but with a design twist. The social card page layout has a bio overview some key stats, connected friends, a photo album. Something simple and nice to delight your users..
        /// </summary>
        internal static string SocialCardPageDescription {
            get {
                return ResourceManager.GetString("SocialCardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classic among modern mobile apps. The social page layout has an overview, some key stats, a photo album, and a cool look and feel..
        /// </summary>
        internal static string SocialPageDescription {
            get {
                return ResourceManager.GetString("SocialPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classic among modern mobile apps. The social page layout has an overview, some key stats, a photo album, and a cool look and feel..
        /// </summary>
        internal static string SocialVariantPageDescription {
            get {
                return ResourceManager.GetString("SocialVariantPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Binaria.
        /// </summary>
        internal static string StringGetGrial {
            get {
                return ResourceManager.GetString("StringGetGrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Binaria Wallet now.
        /// </summary>
        internal static string StringGetGrialNow {
            get {
                return ResourceManager.GetString("StringGetGrialNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your theme.
        /// </summary>
        internal static string StringPickYourTheme {
            get {
                return ResourceManager.GetString("StringPickYourTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A perfect combination of simplicity and functionality. This tabbed page is another great option to include in your app..
        /// </summary>
        internal static string TabbedLoginPageDescription {
            get {
                return ResourceManager.GetString("TabbedLoginPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Android TabControl look and feel also in your iOS application..
        /// </summary>
        internal static string TabControlAndroidSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlAndroidSamplePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a fully customizable Android bottom Tab Control for your app..
        /// </summary>
        internal static string TabControlBottomPlacementSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlBottomPlacementSamplePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Tab Control is fully customizable. Place it anywhere on the screen and get a consistent look and feel across platforms..
        /// </summary>
        internal static string TabControlCustomSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlCustomSamplePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get iOS TabControl look and feel also in your Android application. .
        /// </summary>
        internal static string TabControliOSSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControliOSSamplePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple Tabbed Page sample page..
        /// </summary>
        internal static string TabPageDescription {
            get {
                return ResourceManager.GetString("TabPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean visualization of tasks grouped into projects and workspaces. This page uses Charts for task completion evolution, the Grial Custom Tab Control and Grial Card Views..
        /// </summary>
        internal static string TaskBrowserPageDescription {
            get {
                return ResourceManager.GetString("TaskBrowserPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nice visualization of people performance related to tasks. This page uses Charts and Grial Card Views..
        /// </summary>
        internal static string TaskOverviewPageDescription {
            get {
                return ResourceManager.GetString("TaskOverviewPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bit.ly/2DZUJnS.
        /// </summary>
        internal static string TermsAndConditionsURL {
            get {
                return ResourceManager.GetString("TermsAndConditionsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple page showing all xamarin forms controls styled with current Grial selected theme..
        /// </summary>
        internal static string ThemeOverviewPageDescription {
            get {
                return ResourceManager.GetString("ThemeOverviewPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This timeline is designed to give a clear messaging or conversation overview. Team player collaboration is always a good thing..
        /// </summary>
        internal static string TimelinePageDescription {
            get {
                return ResourceManager.GetString("TimelinePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An eye-catching and interactive page showing a video background with a carousel view that animates and transitions the video colors on swipe over it..
        /// </summary>
        internal static string VideoCarouselHighlightsPageDescription {
            get {
                return ResourceManager.GetString("VideoCarouselHighlightsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Walkthrough is designed to be functional almost in every app. Use it to give users a quick tour through your app..
        /// </summary>
        internal static string WalkthroughFlatPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughFlatPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple but visually appealing walkthrough that calls to action..
        /// </summary>
        internal static string WalkthroughGradientPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughGradientPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simply designed Walkthrough sample. It just displays an image, a description, and a button..
        /// </summary>
        internal static string WalkthroughImagePageDescription {
            get {
                return ResourceManager.GetString("WalkthroughImagePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give instant feedback to app users. Change the message and it will be ready to use in any app..
        /// </summary>
        internal static string WalkthroughMinimalPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughMinimalPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Walkthrough is designed to be functional almost in every app. Use it to give users a quick tour through your app..
        /// </summary>
        internal static string WalkthroughPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Walkthrough is designed to be functional almost in every app. Use it to give users a quick tour through your app..
        /// </summary>
        internal static string WalkthroughVariantPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughVariantPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 160 XAML pages and templates. An infinite set of possibilities to build beautiful apps..
        /// </summary>
        internal static string WhatsNewDescription1 {
            get {
                return ResourceManager.GetString("WhatsNewDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themeable, scalable, Grial Icons provide a huge collection of icons and styles..
        /// </summary>
        internal static string WhatsNewDescription2 {
            get {
                return ResourceManager.GetString("WhatsNewDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid animations, gradient support, flexible layouts, and much more..
        /// </summary>
        internal static string WhatsNewDescription3 {
            get {
                return ResourceManager.GetString("WhatsNewDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Control, Data grid, Checkbox, Radio Button, Video Player, Repeater and more..
        /// </summary>
        internal static string WhatsNewDescription4 {
            get {
                return ResourceManager.GetString("WhatsNewDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include screens in your project and build your own theme through Grial Web Admin..
        /// </summary>
        internal static string WhatsNewDescription5 {
            get {
                return ResourceManager.GetString("WhatsNewDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160+ XAMLs.
        /// </summary>
        internal static string WhatsNewTitle1 {
            get {
                return ResourceManager.GetString("WhatsNewTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 5000 Icons.
        /// </summary>
        internal static string WhatsNewTitle2 {
            get {
                return ResourceManager.GetString("WhatsNewTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richer content.
        /// </summary>
        internal static string WhatsNewTitle3 {
            get {
                return ResourceManager.GetString("WhatsNewTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 New Controls.
        /// </summary>
        internal static string WhatsNewTitle4 {
            get {
                return ResourceManager.GetString("WhatsNewTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Kickstart.
        /// </summary>
        internal static string WhatsNewTitle5 {
            get {
                return ResourceManager.GetString("WhatsNewTitle5", resourceCulture);
            }
        }
    }
}
